###
http://localhost:4000/play/create/testGame

###
http://localhost:4000/play/create/testGame
###
http://localhost:4000/play/getAllGames

###
http://localhost:4000/play/deleteGame


###
http://localhost:4000/play/getCachedGames


###
http://localhost:4000/play/deleteAllPlayers
